FROM openjdk:8u242-jre

RUN curl http://mirrors.ocf.berkeley.edu/apache/rocketmq/4.6.0/rocketmq-all-4.6.0-bin-release.zip -o rocketmq-all-4.6.0-bin-release.zip

RUN unzip rocketmq-all-4.6.0-bin-release.zip

WORKDIR /rocketmq-all-4.6.0-bin-release

ENTRYPOINT  nohup sh bin/mqnamesrv &&  sleep 5 && tail -f ~/logs/rocketmqlogs/namesrv.log